name: GitHub Space Shooter

on:
  schedule:
    - cron: '0 0 * * *' # runs daily
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p output

      - name: Generate Space Shooter
        uses: czl9707/gh-space-shooter@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: output/gh-space-shooter.gif

      - name: Commit & Push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add output/gh-space-shooter.gif
          git commit -m "chore: update space shooter gif [skip ci]" || echo "No changes to commit"
          git push
